---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etl-pt-input
  labels:
    app: etl-pt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etl-pt-output
  labels:
    app: etl-pt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-pt-deployment
  labels:
    app: etl-pt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl-pt
  template:
    metadata:
      labels:
        app: etl-pt
    spec:
      containers:
      - name: app-container
        image: jomaldonadob/etl_pt:tag
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: etl-pt-input
          mountPath: /app/input
        - name: etl-pt-output
          mountPath: /app/output
      volumes:
      - name: etl-pt-input
        persistentVolumeClaim:
          claimName: etl-pt-input
      - name: etl-pt-output
        persistentVolumeClaim:
          claimName: etl-pt-output

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: etl-pt-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etl-pt-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
